### ISSUE TITLE
install step fails

### ISSUE THREAD

**Issue by ajaypanyala** [pulsar-chem/Pulsar-Libint#1]
make install fails with the error

```
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/panyala/git/Pulsar/Pulsar-Libint/build/stage//opt/libraries/pulsar/libint".
```

**Comment by ryanmrichard** [comment]
@bennybp the issue here is we're assuming modules get installed in `/install/path/pulsar/core/lib/pulsar/modules` and consequentially I'm ignoring `CMAKE_INSTALL_PREFIX`.  In hindsight, that's a bad decision.  Perhaps the better solution is if `CMAKE_INSTALL_PREFIX` is not set then modules are default installed into the core's module directory.  Otherwise `CMAKE_INSTALL_PREFIX` is honored.  Thoughts?

**Comment by bennybp** [comment]
My goal was to make the pulsar scripts agnostic to where modules were installed. All that has to be done if the module is installed elsewhere is to add the path to the ModuleAdministrator (`add_path` function). You can also add the path to to the `PYTHONPATH` environment variable (with the `add_path` taking precedence).

So yes, for modules, `CMAKE_INSTALL_PREFIX` should always be honored, with a fallback being the core modules directory.

**Comment by ryanmrichard** [comment]
OK.  My idea doesn't quite work.  CMake by default sets `CMAKE_INSTALL_PREFIX` so there's no way to tell if the user just set it to `/` or if that's the default.  I guess I just have to manually set the `CMAKE_INSTAL_PREFIX` for each module to that of the core's module directory.
